# ./serverless.yml
service: insurtech-api

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  serverless-dynamodb:
    stages:
      - develop
    start:
      host: localhost
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws
  runtime: nodejs18.x
  architecture: arm64
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
  region: eu-west-1
  stage: ${opt:stage}
  timeout: 30
  environment:
    NODE_ENV: ${self:provider.stage}
    USERS_TABLE_NAME: users

package:
  individually: true

functions:
  - ${file(resources/functions.yml)}

resources:
  Resources:
    UsersTable: ${file(resources/dynamo-db.yml):UsersTable}
